In [ ]:
import pandas as pd
import numpy as np

# Pandas
pd.set_option('display.float_format', '{:.15f}'.format)

# NumPy
np.set_printoptions(suppress=True, precision=15)

In [76]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQtBXo5cBnDsM2fmfHPm6u72KGUS5FjPHNGMxOfYjA9-CAhmnRpwkIw_rOR3sANJIToiUU__6fbBvig/pub?gid=572763137&single=true&output=csv")

In [77]:
df.head()

,Time,0,1,2,3,4,5,6,7,8,...,581,582,583,584,585,586,587,588,589,Pass/Fail
0,2008-07-19 11:55:00,3030.929999999999836,2564.000000000000000,2187.733299999999872,1411.126500000000078,1.360200000000000,100.000000000000000,97.613299999999995,0.124200000000000,1.500500000000000,...,NaN,0.500500000000000,0.011800000000000,0.003500000000000,2.363000000000000,NaN,NaN,NaN,NaN,-1
1,2008-07-19 12:32:00,3095.780000000000200,2465.139999999999873,2230.422199999999975,1463.660599999999931,0.829400000000000,100.000000000000000,102.343299999999999,0.124700000000000,1.496600000000000,...,208.204499999999996,0.501900000000000,0.022300000000000,0.005500000000000,4.444700000000000,0.009600000000000,0.020100000000000,0.006000000000000,208.204499999999996,-1
2,2008-07-19 13:17:00,2932.610000000000127,2559.940000000000055,2186.411099999999806,1698.017200000000003,1.510200000000000,100.000000000000000,95.487799999999993,0.124100000000000,1.443600000000000,...,82.860200000000006,0.495800000000000,0.015700000000000,0.003900000000000,3.174500000000000,0.058400000000000,0.048400000000000,0.014800000000000,82.860200000000006,1
3,2008-07-19 14:43:00,2988.719999999999800,2479.900000000000091,2199.033300000000054,909.792599999999993,1.320400000000000,100.000000000000000,104.236699999999999,0.121700000000000,1.488200000000000,...,73.843199999999996,0.499000000000000,0.010300000000000,0.002500000000000,2.054400000000000,0.020200000000000,0.014900000000000,0.004400000000000,73.843199999999996,-1
4,2008-07-19 15:22:00,3032.239999999999782,2502.869999999999891,2233.366700000000037,1326.519999999999982,1.533400000000000,100.000000000000000,100.396699999999996,0.123500000000000,1.503100000000000,...,NaN,0.480000000000000,0.476600000000000,0.104500000000000,99.303200000000004,0.020200000000000,0.014900000000000,0.004400000000000,73.843199999999996,-1

In [78]:
df.isnull().sum()

Time          0
0             6
1             7
2            14
3            14
             ..
586           1
587           1
588           1
589           1
Pass/Fail     0
Length: 592, dtype: int64

In [79]:
# No of rows having atleast one missing value
df.isnull().any(axis=1).sum()

1567

In [80]:
df.isnull().sum(axis=1)

0        44
1        36
2        20
3        20
4        40
       ...
1562     52
1563     52
1564    148
1565     60
1566    152
Length: 1567, dtype: int64

In [81]:
# Filling missing values with random numbers


# Dropping time column
df.drop(columns = ['Time'], inplace = True)

for column in df.columns:
    print(f'Column: {column}')

    # Getting min and max value of the column
    min_value = df[column].min()
    max_value = df[column].max()

    # Generate random numbers withing the range
    random_values = np.random.uniform(low = min_value, high = max_value, size = df[column].isnull().sum())

    # Creating a series with generated random values
    random_series = pd.Series(random_values, index = df[column] [df[column].isnull()].index)

    # Fill NaN values with random values
    df[column].fillna(random_series, inplace = True)

Column: 0
Column: 1
Column: 2
Column: 3
Column: 4
Column: 5
Column: 6
Column: 7
Column: 8
Column: 9
Column: 10
Column: 11
Column: 12
Column: 13
Column: 14
Column: 15
Column: 16
Column: 17
Column: 18
Column: 19
Column: 20
Column: 21
Column: 22
Column: 23
Column: 24
Column: 25
Column: 26
Column: 27
Column: 28
Column: 29
Column: 30
Column: 31
Column: 32
Column: 33
Column: 34
Column: 35
Column: 36
Column: 37
Column: 38
Column: 39
Column: 40
Column: 41
Column: 42
Column: 43
Column: 44
Column: 45
Column: 46
Column: 47
Column: 48
Column: 49
Column: 50
Column: 51
Column: 52
Column: 53
Column: 54
Column: 55
Column: 56
Column: 57
Column: 58
Column: 59
Column: 60
Column: 61
Column: 62
Column: 63
Column: 64
Column: 65
Column: 66
Column: 67
Column: 68
Column: 69
Column: 70
Column: 71
Column: 72
Column: 73
Column: 74
Column: 75
Column: 76
Column: 77
Column: 78
Column: 79
Column: 80
Column: 81
Column: 82
Column: 83
Column: 84
Column: 85
Column: 86
Column: 87
Column: 88
Column: 89
Column: 90
Column: 91
Column: 92
Column: 93
Column: 94
Column: 95
Column: 96
Column: 97
Column: 98
Column: 99
Column: 100
Column: 101
Column: 102
Column: 103
Column: 104
Column: 105
Column: 106
Column: 107
Column: 108
Column: 109
Column: 110
Column: 111
Column: 112
Column: 113
Column: 114
Column: 115
Column: 116
Column: 117
Column: 118
Column: 119
Column: 120
Column: 121
Column: 122
Column: 123
Column: 124
Column: 125
Column: 126
Column: 127
Column: 128
Column: 129
Column: 130
Column: 131
Column: 132
Column: 133
Column: 134
Column: 135
Column: 136
Column: 137
Column: 138
Column: 139
Column: 140
Column: 141
Column: 142
Column: 143
Column: 144
Column: 145
Column: 146
Column: 147
Column: 148
Column: 149
Column: 150
Column: 151
Column: 152
Column: 153
Column: 154
Column: 155
Column: 156
Column: 157
Column: 158
Column: 159
Column: 160
Column: 161
Column: 162
Column: 163
Column: 164
Column: 165
Column: 166
Column: 167
Column: 168
Column: 169
Column: 170

C:\Users\jugal\AppData\Local\Temp\ipykernel_32424\3934066893.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(random_series, inplace = True)

Column: 171
Column: 172
Column: 173
Column: 174
Column: 175
Column: 176
Column: 177
Column: 178
Column: 179
Column: 180
Column: 181
Column: 182
Column: 183
Column: 184
Column: 185
Column: 186
Column: 187
Column: 188
Column: 189
Column: 190
Column: 191
Column: 192
Column: 193
Column: 194
Column: 195
Column: 196
Column: 197
Column: 198
Column: 199
Column: 200
Column: 201
Column: 202
Column: 203
Column: 204
Column: 205
Column: 206
Column: 207
Column: 208
Column: 209
Column: 210
Column: 211
Column: 212
Column: 213
Column: 214
Column: 215
Column: 216
Column: 217
Column: 218
Column: 219
Column: 220
Column: 221
Column: 222
Column: 223
Column: 224
Column: 225
Column: 226
Column: 227
Column: 228
Column: 229
Column: 230
Column: 231
Column: 232
Column: 233
Column: 234
Column: 235
Column: 236
Column: 237
Column: 238
Column: 239
Column: 240
Column: 241
Column: 242
Column: 243
Column: 244
Column: 245
Column: 246
Column: 247
Column: 248
Column: 249
Column: 250
Column: 251
Column: 252
Column: 253
Column: 254
Column: 255
Column: 256
Column: 257
Column: 258
Column: 259
Column: 260
Column: 261
Column: 262
Column: 263
Column: 264
Column: 265
Column: 266
Column: 267
Column: 268
Column: 269
Column: 270
Column: 271
Column: 272
Column: 273
Column: 274
Column: 275
Column: 276
Column: 277
Column: 278
Column: 279
Column: 280
Column: 281
Column: 282
Column: 283
Column: 284
Column: 285
Column: 286
Column: 287
Column: 288
Column: 289
Column: 290
Column: 291
Column: 292
Column: 293
Column: 294
Column: 295
Column: 296
Column: 297
Column: 298
Column: 299
Column: 300
Column: 301
Column: 302
Column: 303
Column: 304
Column: 305
Column: 306
Column: 307
Column: 308
Column: 309
Column: 310
Column: 311
Column: 312
Column: 313
Column: 314
Column: 315
Column: 316
Column: 317
Column: 318
Column: 319
Column: 320
Column: 321
Column: 322
Column: 323
Column: 324
Column: 325
Column: 326
Column: 327
Column: 328
Column: 329
Column: 330
Column: 331
Column: 332
Column: 333
Column: 334
Column: 335
Column: 336
Column: 337
Column: 338
Column: 339
Column: 340
Column: 341
Column: 342
Column: 343
Column: 344
Column: 345
Column: 346
Column: 347
Column: 348
Column: 349
Column: 350
Column: 351
Column: 352
Column: 353
Column: 354
Column: 355
Column: 356
Column: 357
Column: 358
Column: 359
Column: 360
Column: 361
Column: 362
Column: 363
Column: 364
Column: 365
Column: 366
Column: 367
Column: 368
Column: 369
Column: 370
Column: 371
Column: 372
Column: 373
Column: 374
Column: 375
Column: 376
Column: 377
Column: 378
Column: 379
Column: 380
Column: 381
Column: 382
Column: 383
Column: 384
Column: 385
Column: 386
Column: 387
Column: 388
Column: 389
Column: 390
Column: 391
Column: 392
Column: 393
Column: 394
Column: 395
Column: 396
Column: 397
Column: 398
Column: 399
Column: 400
Column: 401
Column: 402
Column: 403
Column: 404
Column: 405
Column: 406
Column: 407
Column: 408
Column: 409
Column: 410
Column: 411
Column: 412
Column: 413
Column: 414
Column: 415
Column: 416
Column: 417
Column: 418
Column: 419
Column: 420
Column: 421
Column: 422
Column: 423
Column: 424
Column: 425
Column: 426
Column: 427
Column: 428
Column: 429
Column: 430
Column: 431
Column: 432
Column: 433
Column: 434
Column: 435
Column: 436
Column: 437
Column: 438
Column: 439
Column: 440
Column: 441
Column: 442
Column: 443
Column: 444
Column: 445
Column: 446
Column: 447
Column: 448
Column: 449
Column: 450
Column: 451
Column: 452
Column: 453
Column: 454
Column: 455
Column: 456
Column: 457
Column: 458
Column: 459
Column: 460
Column: 461
Column: 462
Column: 463
Column: 464
Column: 465
Column: 466
Column: 467
Column: 468
Column: 469
Column: 470
Column: 471
Column: 472
Column: 473
Column: 474
Column: 475
Column: 476
Column: 477
Column: 478
Column: 479
Column: 480
Column: 481
Column: 482
Column: 483
Column: 484
Column: 485
Column: 486
Column: 487
Column: 488
Column: 489
Column: 490
Column: 491
Column: 492
Column: 493
Column: 494
Column: 495
Column: 496
Column: 497
Column: 498
Column: 499
Column: 500
Column: 501
Column: 502
Column: 503
Column: 504
Column: 505
Column: 506
Column: 507
Column: 508
Column: 509
Column: 510
Column: 511
Column: 512
Column: 513
Column: 514
Column: 515
Column: 516
Column: 517
Column: 518
Column: 519
Column: 520
Column: 521
Column: 522
Column: 523
Column: 524
Column: 525
Column: 526
Column: 527
Column: 528
Column: 529
Column: 530
Column: 531
Column: 532
Column: 533
Column: 534
Column: 535
Column: 536
Column: 537
Column: 538
Column: 539
Column: 540
Column: 541
Column: 542
Column: 543
Column: 544
Column: 545
Column: 546
Column: 547
Column: 548
Column: 549
Column: 550
Column: 551
Column: 552
Column: 553
Column: 554
Column: 555
Column: 556
Column: 557
Column: 558
Column: 559
Column: 560
Column: 561
Column: 562
Column: 563
Column: 564
Column: 565
Column: 566
Column: 567
Column: 568
Column: 569
Column: 570
Column: 571
Column: 572
Column: 573
Column: 574
Column: 575
Column: 576
Column: 577
Column: 578
Column: 579
Column: 580
Column: 581
Column: 582
Column: 583
Column: 584
Column: 585
Column: 586
Column: 587
Column: 588
Column: 589
Column: Pass/Fail

In [82]:
df.isnull().sum()

0            0
1            0
2            0
3            0
4            0
            ..
586          0
587          0
588          0
589          0
Pass/Fail    0
Length: 591, dtype: int64

In [83]:
# Seperating features and target variable
x = df.drop(columns = ['Pass/Fail'])
y = df['Pass/Fail']

In [84]:
print(df.shape)
print()

print(x.shape)
print(y.shape)

(1567, 591)

(1567, 590)
(1567,)

# Applying Logistic Regression

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [86]:
# Train test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

print(f"X_train shape: {x_train.shape}")
print(f"X_test shape: {x_test.shape}")

# Initialize and train logistic regression model
lr = LogisticRegression(max_iter = 100000)
lr.fit(x_train, y_train)

# Predicting test data
y_pred = lr.predict(x_test)

# Getting accuracy
acc = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {acc}")

X_train shape: (1253, 590)
X_test shape: (314, 590)
Test Accuracy: 0.8757961783439491

c:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 13434 iteration(s) (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT

You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

To perform filter-based feature selection on the "UCI SECOM" dataset, which has 592 columns and a target column called "Pass/Fail," we can utilize the following methods:

**1. Duplicate Features:**
   - Identify and remove duplicate columns from the dataset. Columns with identical values provide redundant information and do not contribute to the prediction task.

**2. Variance Threshold Method:**
   - Calculate the variance of each feature.
   - Remove features with low variance, as they tend to have little or no predictive power.
   - Set a threshold value for variance and remove features below that threshold.

**3. Correlation:**
   - Compute the correlation matrix of the features.
   - Identify highly correlated features and choose one from each highly correlated group.
   - High correlation between features indicates redundancy, and removing one from each correlated group helps reduce multicollinearity.

**4. ANOVA (Analysis of Variance):**
   - Perform an ANOVA test between each feature and the target variable ("Pass/Fail").
   - Select features with a significant impact on the target variable.
   - Set a significance level (e.g., p-value threshold) for the test to determine the importance of each feature.

**5. Chi-Squared:**
   - Apply the Chi-Squared test between each feature and the target variable, considering both features as categorical.
   - Select features with a significant association with the target variable.
   - Set a significance level (e.g., p-value threshold) to determine the importance of each feature.

`Implementing these feature selection methods in Python using the "UCI SECOM" dataset can be done as follows:`

# `Step 1: `Remove Duplicate columns

In [87]:
from feature_engine.selection import DropDuplicateFeatures

ddf = DropDuplicateFeatures()

x_train = ddf.fit_transform(x_train)
x_test = ddf.transform(x_test)

print(f"""X_train shape: {x_train.shape}
X_test shape: {x_test.shape}""")

# Columns reduced from 590 to 478

X_train shape: (1253, 478)
X_test shape: (314, 478)

In [88]:
x_train.head()

,0,1,2,3,4,5,6,7,8,9,...,580,581,582,583,584,585,586,587,588,589
1005,2945.219999999999800,2570.440000000000055,2194.955599999999777,2341.783300000000054,2.391700000000000,100.000000000000000,86.810000000000002,0.123100000000000,1.420700000000000,0.008600000000000,...,0.015191027288223,729.295607311002527,0.497600000000000,0.016400000000000,0.003500000000000,3.294500000000000,0.055200000000000,0.017800000000000,0.005100000000000,32.205800000000004
858,2938.019999999999982,2499.679999999999836,2114.666700000000219,1549.487399999999980,1.339300000000000,100.000000000000000,98.784400000000005,0.126200000000000,1.444600000000000,-0.010900000000000,...,0.004500000000000,65.218599999999995,0.501400000000000,0.008100000000000,0.002400000000000,1.618000000000000,0.022000000000000,0.014300000000000,0.004500000000000,65.218599999999995
1485,2911.219999999999800,2556.639999999999873,2204.288900000000012,2637.998900000000049,1.554900000000000,100.000000000000000,86.108900000000006,0.123400000000000,1.443900000000000,-0.009400000000000,...,0.006100000000000,178.040500000000009,0.498500000000000,0.015300000000000,0.004100000000000,3.067000000000000,0.010400000000000,0.018500000000000,0.006100000000000,178.040500000000009
382,3047.000000000000000,2436.010000000000218,2213.755599999999959,1113.559899999999971,0.721700000000000,100.000000000000000,104.166700000000006,0.121100000000000,1.560800000000000,-0.000400000000000,...,0.024149046022386,155.655668225968924,0.496400000000000,0.010700000000000,0.003100000000000,2.164600000000000,0.016500000000000,0.031800000000000,0.010200000000000,192.913000000000011
1012,2992.400000000000091,2590.800000000000182,2223.900000000000091,1745.372399999999971,1.997400000000000,100.000000000000000,96.756699999999995,0.124100000000000,1.551900000000000,-0.027300000000000,...,0.025063223553878,365.165054901325846,0.503900000000000,0.015100000000000,0.003700000000000,3.003900000000000,0.016700000000000,0.013200000000000,0.003900000000000,79.108599999999996

# 2) Variance Threshold

**Note**: Always scale all the features first else a single variance threshold will not work for all the features.

- We may have two types of features.
    - `Constant features`: 
        - When in any feature, all values are same, such features are called **constant features**.
        - Such features have 0 variance
    - `Quasi Constant Features`:
        - Suppose there are 1000 rows. In column B, 990 rows has value `No`, only 10 rows has values `Yes`. Such features are called Quassi Constant Features.
        - Such features have variance very near to 0.

As such features have very low variance (almost 0), they cannot help to differentiate target variable. So, we drop such features.

# Steps:
1) `Decide threshold`: This is to be decided based on domain knowledge. <br>
`In general, variance threshold is set between 0.01-0.1`
2) Find variance of all the features independently.
3) If feature_variance < threshold, drop that feature.

In [89]:
# Scaling features

from sklearn.preprocessing import StandardScaler

ss = StandardScaler().set_output(transform = 'pandas')

x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)

In [92]:
# Applying Variance threshold

from sklearn.feature_selection import VarianceThreshold

vt = VarianceThreshold(threshold = 0.05).set_output(transform = 'pandas')

x_train = vt.fit_transform(x_train)
x_test = vt.transform(x_test)

In [98]:
print(f"""X_train shape: {x_train.shape}
X_test shape: {x_test.shape}""")

# Columns reduced from 478 to 474

X_train shape: (1253, 474)
X_test shape: (314, 474)

# 2) Correlation

There are two approach in correlation based filtering.

    1) Between each feature.
        - Find correlation of all the columns with each other.
        - It returns a value between -1 and 1.
        - -1 means strong negative correlation and 1 means strong positive correlation
        - We decide a threshold, say 0.95, if corr between features is >0.95 or <(-0.95), we will drop any one feature from them.
        - We mostly use this approach

    2) Between a feature and target variable.
        - Finds correlation of each feature with the target variable.
        - We then decide a cut off, say 0.3 and -0.3.
        - We keep those features where corr>0.3 and corr<-0.3 (Corr between the feature and target variable)


# 3) Correlation

There are two approach in correlation based filtering.

    1) Between each feature.
        - Find correlation of all the columns with each other.
        - It returns a value between -1 and 1.
        - -1 means strong negative correlation and 1 means strong positive correlation
        - We decide a threshold, say 0.95, if corr between features is >0.95 or <(-0.95), we will drop any one feature from them.
        - We mostly use this approach

    2) Between a feature and target variable.
        - Finds correlation of each feature with the target variable.
        - We then decide a cut off, say 0.3 and -0.3.
        - We keep those features where corr>0.3 and corr<-0.3 (Corr between the feature and target variable)

In [100]:
from feature_engine.selection import DropCorrelatedFeatures

In [108]:
corr_matrix = x_train.corr().abs()

columns = corr_matrix.columns[
    (corr_matrix > 0.95).any()
]

print(columns)

Index(['0', '1', '2', '3', '4', '6', '7', '8', '9', '10',
       ...
       '580', '581', '582', '583', '584', '585', '586', '587', '588', '589'],
      dtype='object', length=474)

In [ ]:
dcf = DropCorrelatedFeatures(threshold = 0.95)

x_train = dcf.fit_transform(x_train)
x_test = dcf.transform(x_test)

print(f"""X_train shape: {x_train.shape}
X_test shape: {x_test.shape}""")

# Columns reduced from 474 to 366

X_train shape: (1253, 366)
X_test shape: (314, 366)

# 4) ANOVA

In [111]:
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectKBest


anova = SelectKBest(f_classif, k = 100).set_output(transform = 'pandas')

In [ ]:
x_train = anova.fit_transform(x_train, y_train)
x_test = anova.transform(x_test)

print(f"""X_train shape: {x_train.shape}
X_test shape: {x_test.shape}""")

# Columns reduced from 366 to 100

X_train shape: (1253, 100)
X_test shape: (314, 100)

In [ ]:
# See the selected columns

# x_train.columns

anova.get_feature_names_out()
# Both gives the same result

100

# Chi-Squared

Our Data is Numerical so chi-squared can't be applied

In [118]:
# Applying Logistic Regression on 100 columns

lr = LogisticRegression()

lr.fit(x_train, y_train)

y_pred = lr.predict(x_test)

acc = accuracy_score(y_test, y_pred)

print(f"Accuracy on 100 columns: {acc}")

Accuracy on 100 columns: 0.9203821656050956

# Conclusion:

Accuracy on all columns--> `0.88`  <br>
Accuracy on 100 columns--> `0.92`

# ThankYou