# What is JSON?

* The full form of JSON is **Java Script On Notation**
* It is a universal accepted file format, understandable by most of the  programming languages.
* The files which we obtain through API(We will learn API in one of our our later sessions) is generally in JSON format.
* pd.read_json()  function is used for reading JSON file.
* Most of the parameters of **read_csv()** are available in **read_json()**.

# What is SQL?

* The full form of SQL is **Sturcture Query Language**.
* Here, we load the dataset in Python directly from the database.

# Working with JSON

In [10]:
import pandas as pd

df = pd.read_json("16 train.json")
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [14]:
# Loading json file from API: Just pass url to read_json.

# Working with SQL data.

* Before loading the sql data on pandas DataFrame, we need to load the downloaded sql file to MYSQL by creating a new file.
* After that we need to import a lbrary **mysql.connector** which connects MySQL with Python.
*

In [16]:
import mysql.connector

In [19]:
mysql.connector.connect(host = 'localhost', user = 'root', password = '', database = 'world')

# By running the above code we'll get the connector's object so we will have to store it into an variable.

In [20]:
connection = mysql.connector.connect(host = 'localhost', user = 'root', password = '', database = 'world')re

In [42]:
df = pd.read_sql_query("SELECT * FROM city", connection)

# 'read_sql_query' also has almmost all the parameters of 'read_csv'.

C:\Users\jugal\AppData\Local\Temp\ipykernel_25180\337090886.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM city", connection)

In [28]:
print(df.head(20))

    ID              Name CountryCode       District  Population
0    1             Kabul         AFG          Kabol     1780000
1    2          Qandahar         AFG       Qandahar      237500
2    3             Herat         AFG          Herat      186800
3    4    Mazar-e-Sharif         AFG          Balkh      127800
4    5         Amsterdam         NLD  Noord-Holland      731200
5    6         Rotterdam         NLD   Zuid-Holland      593321
6    7              Haag         NLD   Zuid-Holland      440900
7    8           Utrecht         NLD        Utrecht      234323
8    9         Eindhoven         NLD  Noord-Brabant      201843
9   10           Tilburg         NLD  Noord-Brabant      193238
10  11         Groningen         NLD      Groningen      172701
11  12             Breda         NLD  Noord-Brabant      160398
12  13         Apeldoorn         NLD     Gelderland      153491
13  14          Nijmegen         NLD     Gelderland      152463
14  15          Enschede         NLD     Overijssel      149544
15  16           Haarlem         NLD  Noord-Holland      148772
16  17            Almere         NLD      Flevoland      142465
17  18            Arnhem         NLD     Gelderland      138020
18  19          Zaanstad         NLD  Noord-Holland      135621
19  20  ´s-Hertogenbosch         NLD  Noord-Brabant      129170

In [37]:
# After creating the dataframe, we can apply all the pandas operation on this SQL file.

df[df['CountryCode'] == 'AFG'].count()

ID             4
Name           4
CountryCode    4
District       4
Population     4
dtype: int64

In [41]:
df[['CountryCode', 'District']]  [df['CountryCode']=="IND"]

     CountryCode        District
1023         IND     Maharashtra
1024         IND           Delhi
1025         IND    West Bengali
1026         IND      Tamil Nadu
1027         IND  Andhra Pradesh
...          ...             ...
1359         IND         Haryana
1360         IND    West Bengali
1361         IND         Gujarat
1362         IND     Chhatisgarh
1363         IND         Gujarat

[341 rows x 2 columns]

# Day 17: Fetching data from an API.