In [2]:
import pandas as pd
from predict import make_batch_predictions
from schema import InputSchema
import numpy as np
np.set_printoptions(suppress=True)

In [35]:
d = [
    {
        'Name': 'Nikunj',
        'Surname': 'Bosamiya',
        'Age': 25
    },
    
    {
        'Name': 'Jugal',
        'Surname': 'Bosamiya',
        'Age': 21
    }
]

In [36]:
pd.DataFrame(d)

     Name   Surname  Age
0  Nikunj  Bosamiya   25
1   Jugal  Bosamiya   21

In [37]:
data = [
    {
    'batting_team': "Mumbai Indians",
    'bowling_team': 'Chennai Super Kings',
    'city': 'Mumbai',
    'runs_left': 50,
    'balls_left': 30,
    'wickets_remaining': 5,
    'total_run_x': 180
    },

    {
    'batting_team': "Punjab Kings",
    'bowling_team': 'sunrisers Hyderabad',
    'city': 'Abu Dhabi',
    'runs_left': 80,
    'balls_left': 65,
    'wickets_remaining': 8,
    'total_run_x': 160
    }
]

data_with_ccr_rrr = []

for d in data:
    pydantic = InputSchema(**d)
    print(pydantic.model_dump())
    data_with_ccr_rrr.append(pydantic.model_dump())

print()
print()

print(data_with_ccr_rrr)

df = pd.DataFrame(data_with_ccr_rrr)

df



# InputSchema(**data[0]).model_dump()

{'batting_team': 'Mumbai Indians', 'bowling_team': 'Chennai Super Kings', 'city': 'Mumbai', 'runs_left': 50, 'balls_left': 30, 'wickets_remaining': 5, 'total_run_x': 180, 'crr': 8.67, 'rrr': 10.0}
{'batting_team': 'Punjab Kings', 'bowling_team': 'Sunrisers Hyderabad', 'city': 'Abu Dhabi', 'runs_left': 80, 'balls_left': 65, 'wickets_remaining': 8, 'total_run_x': 160, 'crr': 8.73, 'rrr': 7.38}


[{'batting_team': 'Mumbai Indians', 'bowling_team': 'Chennai Super Kings', 'city': 'Mumbai', 'runs_left': 50, 'balls_left': 30, 'wickets_remaining': 5, 'total_run_x': 180, 'crr': 8.67, 'rrr': 10.0}, {'batting_team': 'Punjab Kings', 'bowling_team': 'Sunrisers Hyderabad', 'city': 'Abu Dhabi', 'runs_left': 80, 'balls_left': 65, 'wickets_remaining': 8, 'total_run_x': 160, 'crr': 8.73, 'rrr': 7.38}]

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_run_x,crr,rrr
0,Mumbai Indians,Chennai Super Kings,Mumbai,50,30,5,180,8.67,10.00
1,Punjab Kings,Sunrisers Hyderabad,Abu Dhabi,80,65,8,160,8.73,7.38

In [40]:
predictions = make_batch_predictions(df)

In [41]:
predictions

array([[0.07190234, 0.92809766],
       [0.99979127, 0.00020873]])

In [44]:
[pred for pred in predictions]

[array([0.07190234, 0.92809766]), array([0.99979127, 0.00020873])]