# What is group_by? Groupby groups the data and then used to study the groups.

`groupby` is always performed on Categorical column. See, what is the use if we apply on numeric column. In numeric column the data will be continuous ar descrete, there's no sense to create groups of numbers.

When we create a groupby function, it creates a groupby object and then we can apply other functions to this object.

`It's mainly used with aggregation function.`

In [1]:
import pandas as pd
import numpy as np

# Here, we'll learn on `imdb` dataset and will practise on cricket's dataset.

`IMDB dataset is the records of top 1000 movies`

In [2]:
imdb = pd.read_csv("00 imdb_dataset.csv")

imdb.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [3]:
imdb['Genre'].unique()

array(['Drama', 'Crime', 'Action', 'Biography', 'Western', 'Comedy',
       'Adventure', 'Animation', 'Horror', 'Mystery', 'Film-Noir',
       'Fantasy', 'Family', 'Thriller'], dtype=object)

In [4]:
genres = imdb.groupby(by = "Genre")    # This will create groups for each category of Genre. This will create a groupby object

genres

In [5]:
genres.sum()

# Index is Genre and sum() method will sum all the values of the numeric columns

C:\Users\jugal\AppData\Local\Temp\ipykernel_11504\4278573771.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  genres.sum()

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [6]:
imdb[imdb['Genre'] == 'Action']['Runtime'].sum()

# See, we're getting the same result as above

22196

In [12]:
genres.min()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [14]:
genres.mean()

C:\Users\jugal\AppData\Local\Temp\ipykernel_11504\1248226035.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  genres.mean()

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

# Find out top 3 genres by total earnings

In [26]:
imdb.groupby(by = 'Genre').sum()    ['Gross'].sort_values(ascending = False).head(3)

C:\Users\jugal\AppData\Local\Temp\ipykernel_11504\3533290013.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  imdb.groupby(by = 'Genre').sum()    ['Gross'].sort_values(ascending = False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [28]:
# More effecient way. 
# Always perform this method bcz this requires less computation to get the top 3 genres on earnig basis

imdb.groupby(by = 'Genre')  ['Gross'].sum().head(3)

Genre
Action       3.263226e+10
Adventure    9.496922e+09
Animation    1.463147e+10
Name: Gross, dtype: float64

# Find the genre with highest average imdb ratings.

In [39]:
imdb.groupby('Genre')  ['IMDB_Rating'].mean().sort_values(ascending = False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [43]:
imdb.groupby('Genre')  ['IMDB_Rating'].mean().sort_values(ascending = False).idxmax()

# idxmax() only returns the index with highest value, not the value.

'Western'

# Find top 5 most popular directors(Consider no.of votes for popularity).

In [51]:
imdb.groupby('Director')  ['No_of_Votes'].sum().sort_values(ascending = False).head()

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
David Fincher         6607859
Martin Scorsese       6513530
Name: No_of_Votes, dtype: int64

# Find no_of_movies done by each actor

In [65]:
imdb.groupby('Star1')    ['Series_Title'].count().sort_values(ascending = False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Series_Title, Length: 660, dtype: int64

In [66]:
# Using value counts

imdb['Star1'].value_counts()

Tom Hanks          12
Robert De Niro     11
Al Pacino          10
Clint Eastwood     10
Humphrey Bogart     9
                   ..
Preity Zinta        1
Javier Bardem       1
Ki-duk Kim          1
Vladimir Garin      1
Robert Donat        1
Name: Star1, Length: 660, dtype: int64

Index(['George Stevens', 'Jacques Audiard', 'Duncan Jones', 'Tomas Alfredson',
       'Neill Blomkamp', 'Michel Gondry', 'Cristian Mungiu',
       'Richard Schenkman', 'Tarsem Singh', 'Gus Van Sant',
       ...
       'Quentin Tarantino', 'Christopher Nolan', 'Woody Allen', 'Billy Wilder',
       'Stanley Kubrick', 'Akira Kurosawa', 'Martin Scorsese',
       'Hayao Miyazaki', 'Steven Spielberg', 'Alfred Hitchcock'],
      dtype='object', length=548)

# `groupby` attributes and methods.

* find total number of groups -> len()
* find items in each group -> size
* first()/last() -> nth item
* get_group() -> vs filtering
* groups
* describe()
* sample()
* nunique()

# 1) Find total no_of groups--> `len()`

In [75]:
len(imdb.groupby('Genre'))

14

In [76]:
imdb.Genre.nunique()

14

# 2) Find items/rows in each group--> size

In [77]:
imdb.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [78]:
imdb.Genre.value_counts()

Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: Genre, dtype: int64

# 3) Find 1st and last item/ row of each group--> first()/ last()/ nth()

In [80]:
imdb.groupby('Genre').first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [83]:
# last()

imdb.groupby('Genre').last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [90]:
# Find 5th movie of each group

imdb.groupby('Genre').nth(4)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Lord of the Rings: The Two Towers,2002,179,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
Adventure,2001: A Space Odyssey,1968,149,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
Animation,Spider-Man: Into the Spider-Verse,2018,117,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
Biography,The Pianist,2002,150,8.5,Roman Polanski,Adrien Brody,729603,32572577.0,85.0
Comedy,3 Idiots,2009,170,8.4,Rajkumar Hirani,Aamir Khan,344445,6532908.0,67.0
Crime,Cidade de Deus,2002,130,8.6,Fernando Meirelles,Kátia Lund,699256,7563397.0,79.0
Drama,Soorarai Pottru,2020,153,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN
Horror,Night of the Living Dead,1968,96,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
Mystery,Kahaani,2012,122,8.1,Sujoy Ghosh,Vidya Balan,57806,1035953.0,NaN

# 4) `get_group()`--> Get records of particular group

In [95]:
group = imdb.groupby('Genre')

group.get_group('Adventure')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
47,Back to the Future,1985,116,Adventure,8.5,Robert Zemeckis,Michael J. Fox,1058081,210609762.0,87.0
93,Inglourious Basterds,2009,153,Adventure,8.3,Quentin Tarantino,Brad Pitt,1267869,120540719.0,69.0
110,Das Boot,1981,149,Adventure,8.3,Wolfgang Petersen,Jürgen Prochnow,231855,11487676.0,86.0
114,2001: A Space Odyssey,1968,149,Adventure,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
...,...,...,...,...,...,...,...,...,...,...
957,Fear and Loathing in Las Vegas,1998,118,Adventure,7.6,Terry Gilliam,Johnny Depp,259753,10680275.0,41.0
964,Dead Man,1995,121,Adventure,7.6,Jim Jarmusch,Johnny Depp,90442,1037847.0,62.0
966,Apollo 13,PG,140,Adventure,7.6,Ron Howard,Tom Hanks,269197,173837933.0,77.0
984,The Muppet Movie,1979,95,Adventure,7.6,James Frawley,Jim Henson,32802,76657000.0,74.0
991,Kelly's Heroes,1970,144,Adventure,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0

In [96]:
# Using filter method

imdb[imdb['Genre'] == 'Adventure']

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
47,Back to the Future,1985,116,Adventure,8.5,Robert Zemeckis,Michael J. Fox,1058081,210609762.0,87.0
93,Inglourious Basterds,2009,153,Adventure,8.3,Quentin Tarantino,Brad Pitt,1267869,120540719.0,69.0
110,Das Boot,1981,149,Adventure,8.3,Wolfgang Petersen,Jürgen Prochnow,231855,11487676.0,86.0
114,2001: A Space Odyssey,1968,149,Adventure,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
...,...,...,...,...,...,...,...,...,...,...
957,Fear and Loathing in Las Vegas,1998,118,Adventure,7.6,Terry Gilliam,Johnny Depp,259753,10680275.0,41.0
964,Dead Man,1995,121,Adventure,7.6,Jim Jarmusch,Johnny Depp,90442,1037847.0,62.0
966,Apollo 13,PG,140,Adventure,7.6,Ron Howard,Tom Hanks,269197,173837933.0,77.0
984,The Muppet Movie,1979,95,Adventure,7.6,James Frawley,Jim Henson,32802,76657000.0,74.0
991,Kelly's Heroes,1970,144,Adventure,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0

# 5) groups--> This will return a key-value pairs where keys are groups' names and values are the list of dictionary containing those value.

`For eg: {'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44} means,` <br>
`Index 2, 5, 8, 10, 13 etc are Action movies.`

In [101]:
group.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

# 6) `describe()`--> Gives statistical info of the group. Same as series and DataFrame

In [105]:
group.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [106]:
group.describe()  ['IMDB_Rating']

           count      mean       std  min    25%  50%    75%  max
Genre
Action     172.0  7.949419  0.304258  7.6  7.700  7.9  8.100  9.0
Adventure   72.0  7.937500  0.229781  7.6  7.800  7.9  8.100  8.6
Animation   82.0  7.930488  0.253221  7.6  7.700  7.9  8.100  8.6
Biography   88.0  7.938636  0.267140  7.6  7.700  7.9  8.100  8.9
Comedy     155.0  7.901290  0.228771  7.6  7.700  7.9  8.050  8.6
Crime      107.0  8.016822  0.335477  7.6  7.800  8.0  8.200  9.2
Drama      289.0  7.957439  0.267229  7.6  7.700  8.0  8.100  9.3
Family       2.0  7.800000  0.000000  7.8  7.800  7.8  7.800  7.8
Fantasy      2.0  8.000000  0.141421  7.9  7.950  8.0  8.050  8.1
Film-Noir    3.0  7.966667  0.152753  7.8  7.900  8.0  8.050  8.1
Horror      11.0  7.909091  0.311302  7.6  7.700  7.8  8.050  8.5
Mystery     12.0  7.975000  0.310791  7.6  7.675  8.0  8.225  8.4
Thriller     1.0  7.800000       NaN  7.8  7.800  7.8  7.800  7.8
Western      4.0  8.350000  0.420317  7.8  8.175  8.4  8.575  8.8

# 7) `sample()`--> This will return specified no_of random samples of each group

In [115]:
group.sample(2, replace = True)

# Replace = True bcz some groups are only having one record. If False, will throw an error mgs.

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
918,Eastern Promises,2007,100,Action,7.6,David Cronenberg,Naomi Watts,227760,17114882.0,82.0
634,Serenity,2005,119,Action,7.8,Joss Whedon,Nathan Fillion,283310,25514517.0,74.0
851,Deliverance,1972,109,Adventure,7.7,John Boorman,Jon Voight,98740,7056013.0,80.0
798,Interstate 60: Episodes of the Road,2002,116,Adventure,7.7,Bob Gale,James Marsden,29999,174381905.0,NaN
596,Toy Story 4,2019,100,Animation,7.8,Josh Cooley,Tom Hanks,203177,434038008.0,84.0
595,Kaze tachinu,2013,126,Animation,7.8,Hayao Miyazaki,Hideaki Anno,73690,5209580.0,83.0
536,All the President's Men,1976,138,Biography,7.9,Alan J. Pakula,Dustin Hoffman,103031,70600000.0,84.0
338,The Imitation Game,2014,114,Biography,8.0,Morten Tyldum,Benedict Cumberbatch,685201,91125683.0,73.0
240,Dil Chahta Hai,2001,183,Comedy,8.1,Farhan Akhtar,Aamir Khan,66803,300000.0,NaN
509,No Man's Land,2001,98,Comedy,7.9,Danis Tanovic,Branko Djuric,44618,1059830.0,84.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
954,Lola rennt,1998,81,Crime,7.6,Tom Tykwer,Franka Potente,188317,7267585.0,77.0
913,Die Welle,2008,107,Drama,7.6,Dennis Gansel,Jürgen Vogel,102742,924558264.0,NaN
259,Before Sunrise,1995,101,Drama,8.1,Richard Linklater,Ethan Hawke,272291,5535405.0,77.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
899,El cuerpo,2012,112,Mystery,7.6,Oriol Paulo,Jose Coronado,57549,140340673.0,NaN
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0

# 8) nunique()--> Returns the no_of unique values of each group.

In [117]:
group.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

# Some other functions

In [ ]:
# agg(), pasing dictionary: Till now, we were applying single aggregare function like min(), max(), sum() etc
# But if we want, we can also apply multiple aggregate functions using agg() method.

genre