In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.float_format', '{:.2f}'.format)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)

np.set_printoptions(suppress=True, precision=2)

In [3]:
df = pd.read_csv(r"00 deliveries.csv")

df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [5]:
df.shape

(179078, 21)

In [6]:
df.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [13]:
# Find top 10 Batsman in term of runs

df.groupby("batsman") ['batsman_runs'].sum().sort_values(ascending = False).head(5)

batsman
V Kohli      5434
SK Raina     5415
RG Sharma    4914
DA Warner    4741
S Dhawan     4632
Name: batsman_runs, dtype: int64

In [25]:
# Find top 5 batsmax with maximum no of sixes

# See, here we dont need any rows where batsman did nit hit six.
# Our concern is only woth those rows where batsman hit six.
# So, let's first filter those rows

sixes_df = df[(df['batsman_runs'] == 6)]
# sixes

sixes_df.groupby("batsman") ['batsman'].count().sort_values(ascending = False).head()

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
Name: batsman, dtype: int64

In [37]:
# Find batsman with most boundries in death overs

# Same solution as above.
# We are only concerned with boundries in death overs so lets filter rows of 16-20 over so filyer accordingly.
# Then apply groupby on batsman.
# take any one column and count no of rows using count()


death_overs_boundries = df[
    (df['over'].between(16,20)) &
    (df['batsman_runs'].isin([4, 6]))
]

# death_overs_boundries

death_overs_boundries.groupby('batsman') ['batsman'].count().sort_values(ascending = False).head()

batsman
MS Dhoni          340
AB de Villiers    208
RG Sharma         208
KA Pollard        206
V Kohli           160
Name: batsman, dtype: int64

In [50]:
# Find V.Kholi's total runs against all the teams

# We are concerned with only V.Kholi. So lets first filter his matches

v_kohli = df[df['batsman'] == 'V Kohli']

# v_kohli

v_kohli.groupby('bowling_team') ['batsman_runs'].sum().sort_values(ascending = False).reset_index()

               bowling_team  batsman_runs
0          Delhi Daredevils           763
1       Chennai Super Kings           749
2     Kolkata Knight Riders           675
3           Kings XI Punjab           636
4            Mumbai Indians           628
5       Sunrisers Hyderabad           509
6          Rajasthan Royals           370
7           Deccan Chargers           306
8             Gujarat Lions           283
9   Rising Pune Supergiants           188
10            Pune Warriors           128
11   Rising Pune Supergiant            83
12           Delhi Capitals            66
13     Kochi Tuskers Kerala            50

In [60]:
# Create a function which returns the highest score of any batsman in a single match

def get_highest_score(df, batsman):

    filter_matches = df[df['batsman'] == batsman]
    
    highest_score = filter_matches.groupby('match_id') ['batsman_runs'].sum().sort_values(ascending = False).head(1).values[0]

    return highest_score

In [62]:
get_highest_score(df, "CH Gayle")

175

In [63]:
def get_highest_score(df, batsman):

    filter_matches = df[df['batsman'] == batsman]

    highest_score = (
        filter_matches
        .groupby('match_id')['batsman_runs']
        .sum()
        .max()
    )

    return highest_score

In [64]:
get_highest_score(df, "CH Gayle")

175