# Concept.
Here in **Mssing indicator** we'll create a new column which will have values as `True` or `False`.<br>
For eg: There's an `Age` column with some missing values. Then in this case, we'll create a new column named `Age_missing`. Corresponding to filled value in `Age` column, it will have `True` and correspond to null values in `Age` column, it will have False.<br>

***See the below DataFrame for better understanding.***

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Age': [15, 16, np.nan, 14, 25, np.nan, 19, 21, np.nan],
    'Age_missing': ['False', 'False', 'True', 'False', 'False', 'True', 'False', 'False', 'True']
}

In [3]:
pd.DataFrame(data)

    Age Age_missing
0  15.0       False
1  16.0       False
2   NaN        True
3  14.0       False
4  25.0       False
5   NaN        True
6  19.0       False
7  21.0       False
8   NaN        True

# What is the use of this.

Actually this was the method use by one participants' group in some competition and the accuracy of their model really increased. There's not any proper answer regarding how's accuray increasing in this but one conception is that, the model is learning to differentiate between **Missing values and filled values**. <br>

This technique doesn't always work but still one should try if required.<br>
Let's see one simple code.

In [4]:
df = pd.read_csv("00 titanic.csv", usecols = ['Age', 'Fare', 'Survived'])

In [5]:
df.sample(8)

     Survived   Age     Fare
870         0  26.0   7.8958
719         0  33.0   7.7750
350         0  23.0   9.2250
291         1  19.0  91.0792
524         0   NaN   7.2292
687         0  19.0  10.1708
439         0  31.0  10.5000
448         1   5.0  19.2583

In [49]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [6]:
# Train/ test split
x = df.drop(columns = 'Survived', axis = True)
y = df.drop(x, axis = 'columns')

In [7]:
x.head()

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [8]:
y.head()

   Survived
0         0
1         1
2         1
3         1
4         0

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [10]:
x_train.head()

      Age     Fare
497   NaN  15.1000
480   9.0  46.9000
721  17.0   7.0542
106  21.0   7.6500
260   NaN   7.7500

In [11]:
y_train.head()

     Survived
497         0
480         0
721         0
106         1
260         0

# Let's compare accuracies with and without applying `MissingIndicator`.
# Filling  missing value with SimpleImputer

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
si = SimpleImputer(strategy = 'mean')

In [14]:
x_train_trans = si.fit_transform(x_train)
x_test_trans = si.transform(x_test)

In [15]:
x_train_trans

array([[29.89089631, 15.1       ],
       [ 9.        , 46.9       ],
       [17.        ,  7.0542    ],
       ...,
       [26.        , 20.575     ],
       [25.        ,  7.7417    ],
       [40.        , 13.        ]])

In [16]:
# Training the model

from sklearn.linear_model import LogisticRegression

In [17]:
lr = LogisticRegression()

In [18]:
lr.fit(x_train_trans, y_train)

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [19]:
pred_lr = lr.predict(x_test_trans)

In [20]:
# Calculating accuracy.

from sklearn.metrics import accuracy_score

In [21]:
acc_lr = accuracy_score(y_test, pred_lr)
acc_lr

0.6759776536312849

# Using `MissingIndicator`.

In [22]:
from sklearn.impute import MissingIndicator

In [23]:
mi = MissingIndicator()

In [24]:
mi.fit(x_train)

MissingIndicator()

In [25]:
mi.features_    # array[0] indicated that column at 0 position in our dataset has missing values i.e 'Age' and it's true.

array([0], dtype=int64)

In [26]:
x_train_missing = mi.transform(x_train)

# This should have the values as True or False respectively for missing and filled values in Age column.
# Let's create a table to corss-check it

In [27]:
x_train_missing

array([[ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [28]:
x_train_temp = x_train

x_train_temp.insert(2, 'Age_missing', x_train_missing)    # Insert at loc = 2nd,  column = 'column_name', value = 'values'

In [29]:
x_train_temp.sample(10)

      Age     Fare  Age_missing
53   29.0  26.0000        False
236  44.0  26.0000        False
285  33.0   8.6625        False
697   NaN   7.7333         True
885  39.0  29.1250        False
73   26.0  14.4542        False
522   NaN   7.2250         True
83   28.0  47.1000        False
428   NaN   7.7500         True
133  29.0  26.0000        False

In [30]:
# Transfering x_test
x_test_missing = mi.transform(x_test)

In [31]:
x_test_missing

array([[False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False]])

In [32]:
# Adding these new columns to the original x_train and x_test.

x_train['Age_missing'] = x_train_missing
x_test['Age_missing'] = x_test_missing

In [33]:
x_train.sample(10)

      Age     Fare  Age_missing
541   9.0  31.2750        False
276  45.0   7.7500        False
378  20.0   4.0125        False
632  32.0  30.5000        False
861  21.0  11.5000        False
411   NaN   6.8583         True
851  74.0   7.7750        False
396  31.0   7.8542        False
458  50.0  10.5000        False
239  33.0  12.2750        False

In [34]:
x_test.sample(10)

      Age      Fare  Age_missing
240   NaN   14.4542         True
664  20.0    7.9250        False
611   NaN    7.0500         True
746  16.0   20.2500        False
59   11.0   46.9000        False
581  39.0  110.8833        False
782  29.0   30.0000        False
792   NaN   69.5500         True
668  43.0    8.0500        False
681  27.0   76.7292        False

In [ ]:
 # Applying SimpleImputer after MissingIndicator.
si = SimpleImputer()

x_train_trans_2 = si.fit_transform(x_train)
x_test_trans_2 = si.transform(x_test)

In [36]:
x_train_trans_2.shape

(712, 3)

In [37]:
x_train.shape

(712, 3)

In [38]:
# Training the model

lr2 = LogisticRegression()

In [39]:
lr2.fit(x_train_trans_2, y_train)

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [40]:
pred_mi = lr2.predict(x_test_trans_2)

In [41]:
pred_mi

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [42]:
acc_mi = accuracy_score(y_test, pred_mi)
acc_mi

# We can see that accuracy of our model increased from 0.70 to 0.71. But it is not so that everytime accuracy increases. We should always try this method.

0.6871508379888268

# This same process of applying MissingIndicator() can be obtain just by passing `add_indicator` parameter in `SimpleImputer()`.
# Let's see this also.

In [43]:
si3 = SimpleImputer(add_indicator = True)

In [44]:
x_train_trans_3 = si.fit_transform(x_train)
x_test_trans_3 = si.transform(x_test)

In [51]:
x_train_trans_3

array([[29.89089631, 15.1       ,  1.        ],
       [ 9.        , 46.9       ,  0.        ],
       [17.        ,  7.0542    ,  0.        ],
       ...,
       [26.        , 20.575     ,  0.        ],
       [25.        ,  7.7417    ,  0.        ],
       [40.        , 13.        ,  0.        ]])

In [46]:
# Training the model

lr3 = LogisticRegression()

lr3.fit(x_train_trans_3, y_train)

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [47]:
pred3 = lr3.predict(x_test_trans_3)

In [48]:
acc_add_imputer = accuracy_score(y_test, pred3)

acc_add_imputer

0.6871508379888268

# Conclusion:
* Accuracy without applying `MissingIndicator()`: 0.7094972067039106
* Accuracy after applying `MissingIndicator()`: 0.7150837988826816
* Accuracy after passing `add_indicator` parameter in `SimpleImputer()`: 0.7150837988826816

# Note:
* Accuracy of our model increased from **0.7094** before `MissingIndicator()` to **0.7150**  after **MissingIndicator()**.
* Moreover, we are getting same result and accuracy by using `MissingIndicator()` class and by passing `add_indicator` parameter to `SimpleImputer()` class.
# `add_indicator` parameter is also available in KNNImputer() and IterativeImputer() class, which we'll learn next.
# It's advisable to use `add_indicator` parameter bcz it is much cleaner that the other method.