Encoding categorical data means converting qualitative data to quantitative data.<br>
There're two types of categorical data. They're,
1) Nominal: Where there is no order in the data. It is simple qualitative data. For eg. State, Country, Qualities etc... 
2) Ordinal: Where order is available. For eg. Grades(A-B-C-D), Rank(One-Two-Three), Level(First-Second-Third) etc...

As we know, machine learning algorithm only understands numbers, we need to encode categorical data if any. There are two methods used to encode the categorical data.
1) Ordinal encoding (For Ordinal data) and
2) One-Hot Encoding(For Nominal data).

Here, in this session, we'll learn `Ordinal encoding` and in the next session we will learn `One-Hot encoding`.<br>
Today we'll also learn `Label encoding`.<br>

# What is Label encoding?
When we need to encode target variable, we use label encoding whereas while encoding predictor variables, we use `OrdinalEncoding`.<br>
There is a class named **LabelEncoder** in scikitlearn.<br>
* from skearn.preprocessing import LabelEncoder.

# How to decide which encoding to perform, ordinal or one-hot?

See the data, if it is in the order, go for ordinal encoding, else, one-hot encoding.<br>
For eg. There's a column named `Education` in our dataset and the values are among 'HS', 'UG', 'PG'. Then here we can clearly identify that `PG > UG > HS. So we should apply Ordinal encoding and assign 0, 1 and 2 to HS, UG and PG respectively.

# Let's now go for practical example.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("26 customer.csv")
df.sample(5)

    age  gender review education purchased
47   38  Female   Good        PG       Yes
36   34  Female   Good        UG       Yes
22   18  Female   Poor        PG       Yes
16   59    Male   Poor        UG       Yes
10   98  Female   Good        UG       Yes

In [3]:
print(df['review'].unique())
print(df['education'].unique())
print(df['purchased'].unique())

['Average' 'Poor' 'Good']
['School' 'UG' 'PG']
['No' 'Yes']

In [4]:
# Here, we have 3 categorical columns, namely 'gender', review', 'education' and 'purchased'.
# 'gender' has values like 'Female' or 'Male'. So there's no order in this. Hence it is a Nominal column
# 'review' is Ordinal column.(Average-Poor-Good)
#'education' is also ordinal column.(School-UG-PG)
# Purchase is a target variable and has no order(NO and Yes). So Nominal.

# Here we will apply One-Hot encoder for Nominal columns, Ordinal encoder for ordinal columns and LabelEncoder for target(Label) column.

In this video we'll learn `Ordinal encoding` and `Label encoding` . So here, we will deal with `review`, `education` and `purchased` columns.

In [5]:
df = df.iloc[:, 2:]    # All the rows from column 2 to last column
df.sample(5)

     review education purchased
29  Average        UG       Yes
31     Poor    School       Yes
20  Average    School       Yes
11     Good        UG       Yes
13  Average    School        No

In [6]:
x = df.iloc[:, 0:2]
y = df.drop(x, axis = 'columns')

print(x.head())
print()
print()
print()
print(y.head())

    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG



  purchased
0        No
1        No
2        No
3        No
4        No

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories = [['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

# Here, categories is a parameter of OE class and we need to  pass no.of lists we wanna encode.
# The list should be in the order of lower to higher status.

# Here we passed one list as ['Poor', 'Average', 'Good'] bcz we are telling OE class to give lower importance to Poor and highest importance  to good.
# Second list is ['School', 'UG', 'PG'], means give lower imp to School and higher to PG

In [9]:
oe.fit_transform(x)

array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

In [10]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Till now we were making mistake by fitting and transforming both train and test data. We should fit train data and transform both train and test data


# Now we will encode target variable (y) with LabelEncoder

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()
le.fit_transform(y)    # Here it gives the numeric value alphabetically.

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [14]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

# Day 27 - Encoding categorical data(One-Hot encoding)