In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('00 Brainstroke.csv')

In [3]:
df.sample(5)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
4288,47886,Female,43.0,1,0,Yes,Govt_job,Rural,56.94,45.3,Unknown,0
2507,25443,Male,50.0,0,0,No,Private,Urban,160.94,26.7,smokes,0
3713,48652,Female,8.0,0,0,No,children,Urban,83.55,22.4,Unknown,0
1081,28669,Female,32.0,0,0,Yes,Private,Urban,84.63,40.1,Unknown,0
425,6107,Female,5.0,0,0,No,children,Urban,77.88,13.8,Unknown,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [5]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [6]:
new_col_name = {"Residence_type": "residence_type"}
df = df.rename(columns = new_col_name)
df.head(2)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1

# Train/ test split

In [7]:
x = df.iloc[:, 1:11]
y = df.stroke

In [8]:
print(x.sample(3))

print()
print()
print()

print(y.sample(3))

      gender   age  hypertension  heart_disease ever_married work_type  \
1290  Female  49.0             0              0          Yes   Private
303     Male  66.0             0              0          Yes   Private
2239  Female  46.0             0              0          Yes   Private

     residence_type  avg_glucose_level   bmi smoking_status
1290          Rural              82.41  45.4         smokes
303           Rural             242.30  35.3         smokes
2239          Rural              75.09  28.7   never smoked



1125    0
4141    0
2697    0
Name: stroke, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.7)

In [11]:
print(x_train.isnull().sum())

print()
print()
print()

print(x_test.isnull().sum())

gender                0
age                   0
hypertension          0
heart_disease         0
ever_married          0
work_type             0
residence_type        0
avg_glucose_level     0
bmi                  55
smoking_status        0
dtype: int64



gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
residence_type         0
avg_glucose_level      0
bmi                  146
smoking_status         0
dtype: int64

# Let's fill missing value in 'bmi' column.

In [12]:
from sklearn.impute import KNNImputer

In [13]:
knnimputer = KNNImputer()

In [14]:
x_train['bmi'] = knnimputer.fit_transform(x_train[['bmi']])
x_test['bmi'] = knnimputer.transform(x_test[['bmi']])

In [15]:
print(x_train.isnull().sum())

print()
print()
print()

print(x_test.isnull().sum())

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
dtype: int64



gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
dtype: int64

In [16]:
x_train.head(2)

,gender,age,hypertension,heart_disease,ever_married,work_type,residence_type,avg_glucose_level,bmi,smoking_status
1484,Female,3.0,0,0,No,children,Rural,114.88,19.1,Unknown
3685,Female,2.0,0,0,No,children,Urban,82.30,18.8,Unknown

# To do

1) **KNNImputer**
    * bmi
2) **OneHotEncoder**
   * gender
   * ever_married
   * work_type
   * residence_type
   * smoking_status

3) At last `Scaling`
4) Apply `Decision Tree model`

# Creating Column Transformers

In [18]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

In [20]:
# Imputing missing values on 'bmi' using KNNImputer

data_imputer = [
    ('Impute_bmi', KNNImputer(), [8])
]

trans_imputer = ColumnTransformer(transformers = data_imputer, remainder = 'passthrough')

In [28]:
# Applying OneHotEncoder

data_ohe = [
    ("OHE", OneHotEncoder(sparse = False, handle_unknown = 'ignore'), [0, 4, 5, 6, 9])
]

trans_ohe = ColumnTransformer(transformers = data_ohe, remainder = 'passthrough')

In [147]:
# Applying Standard Scaler

data_std_scaler = [
    ("StandardScaling", StandardScaler(), slice(0, 10))
]

trans_scaler = ColumnTransformer(transformers = data_std_scaler)

In [148]:
from sklearn.tree import DecisionTreeClassifier

trans_dt = DecisionTreeClassifier()

# Making Pipeline

In [149]:
from sklearn.pipeline import Pipeline

In [150]:
pipe = Pipeline([
    ('Trans1', trans_imputer),
    ('Trans2', trans_ohe),
    ('Trans3', trans_scaler),
    ('Trans4', trans_dt)
])

# Train and make predictions

In [151]:
pipe.fit(x_train, y_train)

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('Trans1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Impute_bmi', KNNImputer(),
                                                  [8])])),
                ('Trans2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('OHE',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse=False),
                                                  [0, 4, 5, 6, 9])])),
                ('Trans3',
                 ColumnTransformer(transformers=[('StandardScaling',
                                                  StandardScaler(),
                                                  slice(0, 10, None))])),
                ('Trans4', DecisionTreeClassifier())])

In [152]:
# Making prediction

pred = pipe.predict(x_test)

# Here it is predicting only 0 bcz the class variable is imbalaced. Class 0 hase 4861 rows and 1 has only 249 rows.

In [153]:
from sklearn.metrics import accuracy_score\

accuracy = accuracy_score(pred, y_test)
accuracy

0.9513558848196813

In [154]:
df['stroke'].value_counts()

0    4861
1     249
Name: stroke, dtype: int64

# Second Pipeline with KNN model

In [155]:
from sklearn.neighbors import KNeighborsClassifier

trans_knn = KNeighborsClassifier(n_neighbors = 5)

In [156]:
pipe2 = Pipeline([
    ('Trans1', trans_imputer),
    ('Trans2', trans_ohe),
    ('Trans3', trans_scaler),
    ('Trans4', trans_knn)
])

In [157]:
pipe2.fit(x_train, y_train)

C:\Users\jugal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('Trans1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Impute_bmi', KNNImputer(),
                                                  [8])])),
                ('Trans2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('OHE',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse=False),
                                                  [0, 4, 5, 6, 9])])),
                ('Trans3',
                 ColumnTransformer(transformers=[('StandardScaling',
                                                  StandardScaler(),
                                                  slice(0, 10, None))])),
                ('Trans4', KNeighborsClassifier())])

In [158]:
pred2 = pipe2.predict(x_test)

In [159]:
accuracy_knn = accuracy_score(pred, y_test)

accuracy_knn

0.9513558848196813

In [139]:
df_balanced = df[]

SyntaxError: invalid syntax (3864773911.py, line 1)